name: Update README

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "5 0 * * *"
  # Manual triggers with workflow_dispatch
  workflow_dispatch:

jobs:
  build:
    name: Update-waka-stats
    runs-on: ubuntu-latest
    env:
      WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      UPDATE_OPTION: GIST_AND_MARKDOWN
      MARKDOWN_FILE: README.md
      GIST_ID: 5db7183a9e07f1193716cb2b94e5d0e1
      GIST_BARSTYLE: SOLIDLT
      GIST_BARLENGTH: -1
      GIST_TIMESTYLE: SHORT

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go

      - name: Check out repo
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
      - name: Clone and run waka-box
        run: |-
          git clone https://github.com/YouEclipse/waka-box-go-public.git 
          cd waka-box-go-public && go build -o waka ./cmd/box/main.go
          mv ./waka ../ && cd .. && rm -rf waka-box-go-public/

      - name: Commit and push
        run: |-
          ./waka
          git config --global user.email "i@kokecacao.me" && git config --global user.name "Waka-Bot"
          git diff
          git add README.md && git commit -m ":memo: update profile" || exit 0
          git pull && git push
          